#!/bin/bash
pushd "$( dirname "${BASH_SOURCE[0]}" )" > /dev/null || exit
transpiled_outdir=$(greadlink -f conformance_test_data)
popd > /dev/null || exit

nojscwltool --transpiled-outdir "$transpiled_outdir" "$@"
