#!/usr/bin/env python
import argparse
import os
import tempfile
import sys
import subprocess
from os import path

parser = argparse.ArgumentParser()
parser.add_argument("cwl")
parser.add_argument("input")
parser.add_argument("--outdir")
parser.add_argument("--quiet", action='store_true')
parser.add_argument("--transpiled-outdir")
args = parser.parse_args()

if args.transpiled_outdir is None:
    args.transpiled_outdir = tempfile.mkdtemp()

unjsifycwl_cmdline = "unjsifycwl --output %s %s" % (args.transpiled_outdir, args.cwl)
print(unjsifycwl_cmdline, file=sys.stderr)
subprocess.check_call(unjsifycwl_cmdline, shell=True)

outdir_arg = ""

if args.outdir is not None:
    outdir_arg = "--outdir " + args.outdir

cwltool_cmdline = "cwltool --quiet %s %s %s" % (outdir_arg, args.transpiled_outdir + "/" + path.basename(args.cwl), args.input)

print(cwltool_cmdline, file=sys.stderr)
subprocess.check_call(cwltool_cmdline, shell=True)
